name: Sync Lectures to Public Repo

on:
  push:
    branches:
      - main
    paths:
      - '6_sem/probability/lectures/**' # Запуск только при изменениях в этой папке

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Pushing to public repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          # Исходная папка внутри приватного репо
          source-directory: '6_sem/probability/lectures'
          # Имя пользователя и название публичного репо
          destination-github-username: 'Skifv'
          destination-repository-name: 'probability-lectures'
          # Почта для коммита в публичном репо
          user-email: your-email@example.com
          # Ветка в публичном репо
          target-branch: main